name: Build and Deploy JAR to Heroku

# Trigger the workflow on a push to the main branch
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out the repository's code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Set up the Java environment (e.g., JDK 17)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # 3. Build the fat JAR using Maven
      - name: Build with Maven
        run: mvn clean package

      # 4. Install the Heroku CLI
      - name: Install Heroku CLI
        uses: heroku/setup-heroku-cli@v1
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}

      # 5. Deploy the built JAR file to Heroku
      - name: Deploy JAR to Heroku
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: |
          heroku plugins:install java
          heroku jar:deploy target/*.jar --app $HEROKU_APP_NAME
